Sanity check hostname

diff --git a/apply b/apply
--- a/apply
+++ b/apply
@@ -15,6 +15,18 @@ fi
 hn=$1
 shift
 
+if [ `hostname` != $hn ]; then
+    echo "It doesn't look like you're on $hn..."
+    echo -n "Are you sure? "
+    read yn
+    if [ x${yn:0:1} = xy ]; then
+        :
+    else
+        echo "Aborting"
+        exit 1
+    fi
+fi
+
 if [ ! -r manifests/$hn.pp ]; then
     echo "Cannot find manifests/$hn.pp"
     exit 1
